### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by ianhara** [ianhara/prework-study-guide#1]
##User Story
As a bootcamp student
I want all the prework notes to be structured on a webpage
so that I can easily read and find information

##Acceptance Criteria
GIVEN a prework study guide website
WHEN I visit the website in my browser
THEN I see four boxes titled HTML, CSS, Git, and JavaScript with the associated notes listed

**Comment by Elitsuv** [comment]
Do you want to create a website that contains all codes/notes for HTML?

**Comment by ianhara** [comment]
Well I’m doing so for a boot camp but ultimately yes!

**Comment by Elitsuv** [comment]
great lets see i can contribute in this project or not!

**Comment by ianhara** [comment]
Did you find me on GitHub? I’m a junior in computer science and know Java
and OOP but this full stack dev is new

**Comment by Elitsuv** [comment]
Github

**Comment by ianhara** [comment]
I am going to build my own separate website to learn HTML

**Comment by ianhara** [comment]
JavaScript and CSS as well

**Comment by Elitsuv** [comment]
cool
